name-template: 'v$NEXT_PATCH_VERSION Solar AC Controller'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '✨ New Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '⚡ Improvements'
    labels:
      - 'enhancement'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## Changes
  $CHANGES